### ISSUE TITLE
Support testing on Windows

### ISSUE THREAD

**Issue by cxw42** [cxw42/Test-OnlySome#11]
- [x] `bin/osprove` is only the name of an executable on POSIX.  Invoke it via `perl` instead of directly so it will work on Windows.  E.g., https://ci.appveyor.com/project/cxw42/test-onlysome/builds/20930006#L206 **Edit** we can invoke the batch file.
- [x] (general robustness) don't `die` if a YAML file can't be loaded.  E.g., https://ci.appveyor.com/project/cxw42/test-onlysome/builds/20930006#L212
- [x] `T::OS::PathCapsule`: Add `clone()`
